services:
  mysql:
    image: mysql:8.0
    container_name: assignment11-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: assignment11
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  backend:
    image: codeykenny/backend-repo:${IMAGE_TAG:-latest}
    container_name: assignment11-backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: assignment11
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:

